/*
 *	Take in a txt file generated by MNISTDataToTxt.cpp, and output
 *	arff file which can be accepted by weka directly.
 *
 *	Usage:
 *		MNISTTxtToArff INPUT_FILE
 * */
#include<stdio.h>
#include<string.h>
int main(int argc,char** argv){
	if(argc!=2){
		printf("txt file name required\n");
		return 1;
	}
	if(!freopen(argv[1],"r",stdin) || 
			!freopen("MNIST.arff","w",stdout)){
		printf("cannot open file\n");
		return 1;
	}
	int row=28,col=28;
	char s[4000];
	printf("@relation MNIST\n");
	for(int i=0;i<28*28;i++)
		printf("@attribute a%d numeric\n",i);
	printf("@attribute ans {0,1,2,3,4,5,6,7,8,9}\n");
	printf("@data\n");
	while(1){
		char*t=gets(s);
		if(!t)break;
		puts(s);
	}
	return 0;
}
